---
# tasks file for lighthouse-role
- name: Install EPEL-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Install Nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
- name: Get Lighthouse from Git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: "{{ lighthouse_path }}"
- name: Configure Lighthouse
  become: true
  ansible.builtin.template:
    src: templates/nginx_config.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Restart Nginx service
- name: Flush handlers
  ansible.builtin.meta: flush_handlers